### ISSUE TITLE
fileName Attribute appears to be lost when recursing into parent class

### ISSUE THREAD

**Issue by brad-jones** [goaop/parser-reflection#8]
Hi There,

I have done a very quick test case to highlight my issue:
https://gist.github.com/brad-jones/392122e55f751d8497fc

Just git clone the above and run composer install, then run test.php
You will see something like:

```
Warning: file_get_contents(): Filename cannot be empty in /var/www/vhosts/parser-test/vendor/goaop/parser-reflection/src/ReflectionEngine.php on line 190
PHP Fatal error:  Uncaught Go\ParserReflection\ReflectionException: Namespace Symfony\Component\Console\Command was not found in the file  in /var/www/vhosts/parser-test/vendor/goaop/parser-reflection/src/ReflectionEngine.php:218
Stack trace:
#0 /var/www/vhosts/parser-test/vendor/goaop/parser-reflection/src/ReflectionFileNamespace.php(77): Go\ParserReflection\ReflectionEngine::parseFileNamespace(NULL, 'Symfony\\Compone...')
#1 /var/www/vhosts/parser-test/vendor/goaop/parser-reflection/src/ValueResolver/NodeExpressionResolver.php(236): Go\ParserReflection\ReflectionFileNamespace->__construct(NULL, 'Symfony\\Compone...')
#2 /var/www/vhosts/parser-test/vendor/goaop/parser-reflection/src/ValueResolver/NodeExpressionResolver.php(118): Go\ParserReflection\ValueResolver\NodeExpressionResolver->resolveExprConstFetch(Object(PhpParser\Node\Expr\ConstFetch))
#3 /var/www/vhosts/parser-test/vendor/goaop/parser-reflection/src/ValueResolver/NodeExpressionResolver.php(99): Go\ParserReflection\ValueResolver\NodeExpressionResolver->resolve(Obje in /var/www/vhosts/parser-test/vendor/goaop/parser-reflection/src/ReflectionEngine.php on line 218
```

**Comment by lisachenko** [comment]
Nice catch! Will fix this now.

**Comment by lisachenko** [comment]
Should be fixed now in 1.0.2, run `composer update`

**Comment by lisachenko** [comment]
Thank you for reporting!

```
  - Parameters [1] {
    Parameter #0 [ <optional> $name = NULL ]
  }
```

**Comment by brad-jones** [comment]
Thanks @lisachenko, works beautifully.
